//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zoo
    {
        public string year { get; set; }
        public string month { get; set; }
        public string cash { get; set; }
        public string multicard { get; set; }
        public string ticket { get; set; }
        public string people { get; set; }
    }
}
